export const LOG_OUT = 'LOG_OUT';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const USER_SET_EVENTS = 'USER_SET_EVENTS';
export const USER_SET_CURRENT_EVENT = 'USER_SET_CURRENT_EVENT';

export const MQTT_SET_CLIENT = 'MQTT_SET_CLIENT';
export const MQTT_ADD_MESSAGE = 'MQTT_ADD_MESSAGE';
