export const AUTH_SIGNIN = 'AUTH_SIGNIN';

export const USER_GET_EVENTS = 'USER_GET_EVENTS';
export const USER_GET_SINGLE_EVENT = 'USER_GET_SINGLE_EVENT';
export const USER_CREATE_EVENT = 'USER_CREATE_EVENT';
export const USER_CREATE_GROUP = 'USER_CREATE_GROUP';
export const USER_SUBSCRIBE_CLASS = 'USER_SUBSCRIBE_CLASS';
export const USER_UPLOAD_IMAGES = 'USER_UPLOAD_IMAGES';
